name:                snake-haskell
version:             1.0.0.0
github:              "Jubarte27/snake-haskell"
author:              "Matheus Machado"
maintainer:          "matheusmazar@gmail.com"
copyright:           "2022 Matheus Machado"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Jubarte27/snake-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random
- containers


library:
  source-dirs: src

executables:
  snake-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snake-haskell
